name: Close pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  clean:
    name: Delete preview database branch
    runs-on: ubuntu-latest
    steps:

      - name: Delete Neon branch
        uses: neondatabase/delete-branch-action@v3
        with:
          branch: preview/${{ github.head_ref }}
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
