name: Pull request pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - main

jobs:
  pre-build:
    name: Pre-build checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Formatter
        run: npm run format:check

  deploy:
    name: Preview deployment
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    needs: [pre-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm install --global vercel@latest

      - name: Pull environment variables
        run: |
          vercel env pull .env --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        id: deploy
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > url.txt
          echo "url="$(cat url.txt)"" >> $GITHUB_OUTPUT
